name: fitness_tracker
description: "AI Fitness & Nutrition Tracker - A comprehensive health app with personalized workout & meal plans"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  # google_fonts: ^6.2.1  # Temporarily disabled due to network issues
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  auto_route: ^8.0.3
  go_router: ^14.2.7

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.4.2

  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.4

  # Charts & Graphs
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^24.2.7

  # Voice & Audio
  # speech_to_text: ^6.6.2  # Temporarily disabled due to compilation issues
  flutter_tts: ^3.8.5
  permission_handler: ^11.3.1

  # Image & Camera
  image_picker: ^1.0.7
  image_cropper: ^8.0.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  dartz: ^0.10.1

  # Animation & Gestures
  flutter_animate: ^4.5.0
  flutter_swipe_action_cell: ^3.0.1

  # AI Integration
  google_generative_ai: ^0.4.6
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

